[package]
name = "gateway"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { workspace = true }
tokio = { workspace = true }
sqlx = { workspace = true }
anyhow = { workspace = true }
dotenvy = { workspace = true }
auth = { path = "../modules/auth" }
